theme: minima
title: Greek Learner Texts Project
author: The GLTP Team
description: organising collaboration on Ancient Greek texts and data for learners
header_pages:
  - texts.md
  - other_data.md
  - tools.md
permalink: pretty
google_analytics: UA-175899-17
minima:
  skin: gltp
